name: CICD using Git actions/checkout
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Build Project
        run: npm run build
      - name: Deploy
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain kind-building.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.surge_email}}
          SURGE_TOKEN: ${{secrets.surge_token}}